### PR TITLE
A few corrections

### PR DESCRIPTION
**Pull request by jordi-prats**
I think you might be interested in these corrections:

- the fix for some integer division issues
- the correction of the longwave coefficient for cloud_mode=3 and cloud_mode=4
- a correction of the equation adding snow to the surface layer when there is no ice

Best,
Jordi

### CODE REVIEW

**Comment by matthipsey** [comment]
Hey Jordi
Thanks a lot for finding these issues and the fixes, much appreciated ... I'll double check over them (but I think your right in all cases), and then we will merge into our master. 
Cheers
Matt

**Comment by mcxmcx** [comment]
Dear Jordi:

   I wonder the L_outfl and W_outfl are the length and width of semi-axis or axis?

Cheers

**Comment by jordi-prats** [comment]
Of course Matt, glad to help.
However, as noticed by mcxmcx, I got it wrong with the 11f58c6 commit(Fix basin length at outflow height). Thanks for pointing it out, mcxmcx.

**Comment by rqthomas** [comment]
@matthipsey @casper-boon can this PR be closed so there isn't an open PR from 2017?

**Pull request closed without merging**
